# Generated by Django 3.1.3 on 2024-04-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='damage_result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
